# Generated by Django 3.2.3 on 2021-06-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210606_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='img',
            field=models.ImageField(null=True, upload_to='', verbose_name='Картинка'),
        ),
    ]
