# Generated by Django 3.2.3 on 2021-06-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comment_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер карты')),
                ('username', models.CharField(max_length=100, verbose_name='Имя на карточке')),
            ],
        ),
    ]
