# Generated by Django 3.2.3 on 2021-06-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Логин')),
                ('password', models.TextField(verbose_name='Пароль')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('name', models.CharField(max_length=150, verbose_name='Имя пользователя')),
                ('secondname', models.CharField(max_length=150, verbose_name='Фамилия')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='day',
            field=models.IntegerField(null=True, verbose_name='День истечения времени'),
        ),
        migrations.AddField(
            model_name='card',
            name='month',
            field=models.IntegerField(null=True, verbose_name='Месяц истечения времени'),
        ),
        migrations.AddField(
            model_name='card',
            name='num',
            field=models.IntegerField(null=True, verbose_name='CVV2/CVC2'),
        ),
    ]
