# Generated by Django 3.2.3 on 2021-06-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210607_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='day',
        ),
        migrations.AddField(
            model_name='card',
            name='year',
            field=models.IntegerField(null=True, verbose_name='Год истечения времени'),
        ),
    ]
