# Generated by Django 3.2.3 on 2021-06-07 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_comment_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
